name: bookazon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  lottie: ^2.5.0
  modal_progress_hud_nsn: ^0.4.0
  otp_text_field: ^1.1.3
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/json/
    - lib/resources/constants/app_assets.dart

flutter_intl:
  enabled: true
  arb_dir: lib/resources/localization/l10n
  output_dir: lib/resources/localization/generated

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo750.png

flutter_assets:
  assets_path: assets/
  output_path: lib/resources/constants/
  filename: app_assets.dart
  field_prefix: null
